Ajustes de textos y diseño
clcert/psifos-frontend pull request #14
Opened 2023-03-21 14:41 UTC by camilog

Tiene pequeños cambios de texto, y algunos ajustes a la interfaz

2023-03-21 15:19 UTC, camilog commented
@JaramilloCris Aún no lo aceptes, voy a hacer algunos otros cambios

2023-03-22 14:53 UTC, camilog commented
Ahora sí está listo @jaramillo-cris

2023-03-22 15:48 UTC, JaramilloCris requested changes

2023-03-22 15:48 UTC, JaramilloCris commented on src/pages/Booth/Panel/components/UrnaTable.jsx
>        </Thead>
La condición `props.electionData.election.max_weight > 1` podría dejarse fuera, algo del estilo
`const isShowWeightColumn = props.electionData.election.max_weight > 1`
y luego usarla en las dos partes

2023-03-22 15:49 UTC, camilog commented on src/pages/Booth/Panel/components/UrnaTable.jsx
>        </Thead>
Me parece, lo corregiré

2023-03-22 16:16 UTC, camilog commented on src/pages/Booth/Panel/components/UrnaTable.jsx
>        </Thead>
Fix by [afc1d17](https://github.com/clcert/psifos-frontend/pull/14/commits/afc1d17aaf084623dafd1fc913bef093cf5ff98f)

2023-03-22 18:13 UTC, merged